#!/bin/bash

### Author Satyg
### GitHub - https://github.com/satyg-66
### Date of last change: 2022-06-01
### Date of last verification: 2022-06-01

function ubuntu22_install(){
    # Replace firefox snap with regular firefox
    snap disable firefox
    snap remove --purge firefox
    add-apt-repository ppa:mozillateam/ppa -y
    echo '
    Package: *
    Pin: release o=LP-PPA-mozillateam
    Pin-Priority: 1001
    ' | tee /etc/apt/preferences.d/mozilla-firefox
    apt install -t 'o=LP-PPA-mozillateam' firefox
}

# Update & upgrade system followed by installing software
function install_apps(){
  echo "[ ##### UPDATING & UPGRADING SYSTEM ##### ]"
  apt-get update && apt-get upgrade -y
  while read -r p ; do apt-get install -y $p ; done < <(cat << "EOF"
      vim
      terminator
      texlive-extra
      texlive-formats-extra
      texlive-lang-english
      texstudio
      gnome-tweaks
      gnome-shell-extensions
      gnome-shell-extension-prefs
      gnome-shell-extension-manager
      gnome-shell-extension-dash-to-panel
      pinta
EOF
  )

  # Installing snaps
  echo "[ ##### INSTALLATION SNAPS ##### ]"
  snap install codium --classic
  snap install discord telegram-desktop

  # Git clone Nord GNOME theme, icons and Nord theme firefox
  echo "[ ##### DOWNLOADING THEMES ##### ]"
  tar -xf nordic-darker.tar.xz
  mv /home/"$RUID"/ubuntu-20.04-post-installation/Nordic-darker /usr/share/themes
  rm nordic-darker.tar.xz
  git clone https://github.com/EliverLara/firefox-nordic-theme.git
  chown -R "$RUID":"$RUID" /home/"$RUID"/ubuntu-post-installation/firefox-nordic-theme/
}

# Running commands to clean up
function cleanup(){
  echo "[ ##### CLEANING UP ##### ]"
  apt-get autoremove -y && apt-get autoclean
}

### START ###

# Prompt user to run as root or sudo
if [ "$EUID" -ne 0 ]
  then echo "You need sudo!"
  exit
fi

# Get the Real Username and UID
RUID=$(who | awk 'FNR == 1 {print $1}')
RUSER_UID=$(id -u ${RUID})

# Checking if ubuntu 22.04
OUTPUT=$(lsb_release -r)
SUB='22'

if [[ "$OUTPUT" =~ .*"$SUB".* ]]; then
    ubuntu22 

# Calling function to install apps
install_apps
# Calling function to cleanup
cleanup
# Running settings script
su -c "source /home/"$RUID"/ubuntu-post-installation/settings" - "$RUID"

echo "[ ##### INSTALLATION COMPLETE! ##### ]"
echo "For dash-to-panel to work you need to logout and back in again. Hence, manual configuration is needed!"

read -p '[+] Do you wish to delete the scripts now when they are done? (Y/N): ' yn
yn=$(echo $yn | tr '[:lower:]' '[:upper:]')

if [ "$yn" = "N" ] ; then
    exit 0
else
    # Removing all scripts
    rm -rf /home/"$RUID"/ubuntu-post-installation
fi

### END ###