#!/bin/bash

### Author Satyg
### GitHub - https://github.com/satyg-66
### Date of last change: 2022-06-01
### Date of last verification: 2022-06-01

function ubuntu22_install(){
    # Replace firefox snap with regular firefox
    echo '
    Package: firefox*
    Pin: release o=LP-PPA-mozillateam
    Pin-Priority: -1
    ' | tee /etc/apt/preferences.d/mozilla-firefox
    apt purge firefox
    snap remove firefox
    add-apt-repository ppa:mozillateam/ppa
    apt-get update
    apt-get install firefox
    echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox
}

# Update & upgrade system followed by installing software
function install_apps(){
  echo "[ ##### UPDATING & UPGRADING SYSTEM ##### ]"
  apt-get update && apt-get upgrade -y
  while read -r p ; do apt-get install -y $p ; done < <(cat << "EOF"
      vim
      terminator
      texlive-extra
      texlive-formats-extra
      texlive-lang-english
      texstudio
      gnome-tweaks
      gnome-shell-extensions
      gnome-shell-extension-prefs
      gnome-shell-extension-manager
      gnome-shell-extension-dash-to-panel
      pinta
EOF
  )

  # Installing snaps
  echo "[ ##### INSTALLATION SNAPS ##### ]"
  snap install codium --classic
  snap install discord telegram-desktop

  # Removing pre-installed apps
  apt purge aisleriot cheese gnome-mahjongg gnome-mines gnome-sudoku rhythmbox shotwell -y
  
  # Git clone Nord GNOME theme, icons and Nord theme firefox
  echo "[ ##### DOWNLOADING THEMES ##### ]"
  mkdir /home/"$RUID"/.themes && chown "$RUID":"$RUID" /home/"$RUID"/.themes
  mkdir /home/"$RUID"/.icons && chown "$RUID":"$RUID" /home/"$RUID"/.icons
  tar -xf nordic.tar.xz
  mv /home/"$RUID"/ubuntu-post-installation/Nordic /home/"$RUID"/.themes
  tar -xf nordic-standard-buttons.tar.xz
  mv /home/"$RUID"/ubuntu-post-installation/Nordic-standard-buttons /home/"$RUID"/.icons
  git clone https://github.com/EliverLara/firefox-nordic-theme.git
  chown -R "$RUID":"$RUID" /home/"$RUID"/ubuntu-post-installation/firefox-nordic-theme/
}

# Running commands to clean up
function cleanup(){
  echo "[ ##### CLEANING UP ##### ]"
  apt-get autoremove -y && apt-get autoclean
}

### START ###

# Prompt user to run as root or sudo
if [ "$EUID" -ne 0 ]
  then echo "You need sudo!"
  exit
fi

# Get the Real Username and UID
RUID=$(who | awk 'FNR == 1 {print $1}')
RUSER_UID=$(id -u ${RUID})

# Checking if ubuntu 22.04
OUTPUT=$(lsb_release -r)
SUB='22'

if [[ "$OUTPUT" =~ .*"$SUB".* ]]; then
    ubuntu22 
fi

# Calling function to install apps
install_apps

# Calling function to cleanup
cleanup

# Running settings script
su -c "source /home/"$RUID"/ubuntu-post-installation/settings" - "$RUID"

echo "[ ##### INSTALLATION COMPLETE! ##### ]"
echo "For dash-to-panel to work you need to logout and back in again. Hence, manual configuration is needed!"

read -p '[+] Do you wish to delete the scripts now when they are done? (Y/N): ' yn
yn=$(echo $yn | tr '[:lower:]' '[:upper:]')

if [ "$yn" = "N" ] ; then
    exit 0
else
    # Removing all scripts
    rm -rf /home/"$RUID"/ubuntu-post-installation
fi

### END ###
