#!/bin/bash

### Author Satyg
### GitHub - https://github.com/satyg-66
### Date of last change: 2022-06-01
### Date of last verification: 2022-06-01

function ubuntu22_settings(){
    # Config file to decrese gnome window border fatness
    mv /home/"$RUID"/ubuntu-post-installation/gtk.css /home/"$RUID"/.config/gtk-3.0/gtk.css
    DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$RUSER_UID/bus" gsettings set org.gnome.shell.ubuntu color-scheme "prefer-dark"
    DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$RUSER_UID/bus" gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

    # Minimize app window when clicking on clock
    DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$RUSER_UID/bus" gsettings set org.gnome.shell.extensions.dash-to-dock click-action minimize

    # Hide desktop icons
    DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$RUSER_UID/bus" gsettings set org.gnome.shell.extensions.ding show-home false

    # Setting wallpaper
    echo "[ ##### SETTING WALLPAPER ##### ]"
    mkdir /home/"$RUID"/Pictures/Wallpapers
    mv /home/"$RUID"/ubuntu-post-installation/wallpaper.png /home/"$USER"/Pictures/Wallpapers/wallpaper.png && sleep 1
    DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$RUSER_UID/bus" gsettings set org.gnome.desktop.background picture-uri-dark /home/"$RUID"/Pictures/Wallpapers/wallpaper.png
    echo "Wallpaper is set! Proceeding..."

    # Setting Gnome Theme
    echo "[ ##### SETTING GNOME THEME ##### ]"
    DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$RUSER_UID/bus" gsettings set org.gnome.desktop.interface gtk-theme "Nordic-darker"
    DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$RUSER_UID/bus" gsettings set org.gnome.desktop.interface icon-theme "Nordic-darker-standard-buttons"
    echo "GNOME theme is set! Proceeding..."

    # Configure terminator terminal emulator
    echo "[ ##### CONFIGURING TERMINATOR ##### ]"
    mkdir -p /home/"$RUID"/.config/terminator
    mv /home/"$RUID"/ubuntu-post-installation/config /home/"$RUID"/.config/terminator/config
    echo "Terminator is configured! Proceeding..."

    # Configuring Firefox theme
    echo "[ ##### CONFIGURING FIREFOX ##### ]"
    cd /home/"$RUID"/ubuntu-post-installation/firefox-nordic-theme/
    source /scripts/install.sh
    cd ..
    rm -rf firefox-nordic-theme
    echo "Firefox is configured! Proceeding..."

    # Configuring vim
    echo "[ ##### CONFIGURING VIM ##### ]"
    cp /etc/vim/vimrc /home/"$RUID"/.vimrc
    echo "set number" >> /home/"$RUID"/.vimrc
}

function ubuntu20_settings(){
    # Config file to decrese gnome window border fatness
    mv /home/"$RUID"/ubuntu-post-installation/gtk.css /home/"$RUID"/.config/gtk-3.0/gtk.css
    DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$RUSER_UID/bus" gsettings set org.gnome.shell.extensions.desktop-icons show-home false

    # Setting wallpaper
    echo "[ ##### SETTING WALLPAPER ##### ]"
    mkdir /home/"$RUID"/Pictures/Wallpapers
    mv /home/"$RUID"/ubuntu-post-installation/wallpaper.png /home/"$USER"/Pictures/Wallpapers/wallpaper.png && sleep 1
    DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$RUSER_UID/bus" gsettings set org.gnome.desktop.background picture-uri /home/"$RUID"/Pictures/Wallpapers/wallpaper.png
    echo "Wallpaper is set! Proceeding..."

     # Configure terminator terminal emulator
    echo "[ ##### CONFIGURING TERMINATOR ##### ]"
    mkdir -p /home/"$RUID"/.config/terminator
    mv /home/"$RUID"/ubuntu-post-installation/config /home/"$RUID"/.config/terminator/config
    echo "Terminator is configured! Proceeding..."

    # Setting Gnome theme
    echo "[ ##### SETTING GNOME THEME ##### ]"
    DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$RUSER_UID/bus" gsettings set org.gnome.desktop.interface gtk-theme "Nordic-darker"
    echo "GNOME theme is set! Proceeding..."

    # Configuring Firefox theme
    echo "[ ##### CONFIGURING FIREFOX ##### ]"
    cd /home/"$RUID"/ubuntu-post-installation/firefox-nordic-theme/
    source /scripts/install.sh
    cd ..
    rm -rf firefox-nordic-theme
    echo "Firefox is configured! Proceeding..."

    # Configuring vim
    echo "[ ##### CONFIGURING VIM ##### ]"
    cp /etc/vim/vimrc /home/"$RUID"/.vimrc
    echo "set number" >> /home/"$RUID"/.vimrc
}

# Get the Real Username and UID
RUID=$(who | awk 'FNR == 1 {print $1}')
RUSER_UID=$(id -u ${RUID})

# Checking if ubuntu 22.04
OUTPUT=$(lsb_release -r)
SUB='22'

if [[ "$OUTPUT" =~ .*"$SUB".* ]]; then
    ubuntu22_settings && exit
else
    ubuntu20_settings && exit
fi

